[build]
  publish = "."
  
[build.environment]
  NODE_VERSION = "18"

# Redirect root to main application
[[redirects]]
  from = "/"
  to = "/teltonika_excel_generator.html"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/teltonika_excel_generator.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"